# Configuration file for Jekyll

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Notes
description: Notes and References
url: https://notes.labinojha.com.np # Base URL for your GitHub Pages site

# GitHub Pages specific settings
remote_theme: pages-themes/slate@v0.2.0
markdown: kramdown # Markdown parser to use